### ISSUE TITLE
Glitch CCAM title 

### ISSUE THREAD

**Issue by garrett-laroy-johnson** [parkerdavis1/CCAM#1]
need some simple JS to modify fonts of random letters in "Center for Concrete and Abstract Machines" subtitle. @garrett-laroy-johnson can do this, need font list (and ttf or source) from @ioanbutiu

**Comment by ioanbutiu** [comment]
@garrett-laroy-johnson finally got some of the changes i've been working on pushed to the main branch, the fonts are all ready to use! I manually set the static type for the homepage title for now.

classes for the sans font are `font-sans font-medium` and for the pixelated font `font-moonbase mbsq` (for square version) and `font-moonbase mbrd` (for rounded version). I also manually set the font size for moonbase so it lines up better with the sans font but i wouldn't worry too much about that.

**Comment by ioanbutiu** [comment]
![CleanShot 2024-01-02 at 16 17 14@2x](https://github.com/parkerdavis1/CCAM/assets/36743419/363ab6c5-2ffa-438c-a311-dc5448e7b88a)

could try randomizing colors as well if you want?

**Comment by ioanbutiu** [comment]
@parkerdavis1 I still need to buy licenses for the fonts. i can swap them out with woff files when i do

**Comment by garrett-laroy-johnson** [comment]
I see where everything is in index.astro, but wondering where I should add my <script></script>? @parkerdavis1

**Comment by parkerdavis1** [comment]
Scripts can just be added to the bottom of that index.astro file (https://docs.astro.build/en/guides/client-side-scripts/) but I'll split it out into a component for cleanliness

**Comment by parkerdavis1** [comment]
Also, I have a feeling that we might fundamentally change how these letters are rendered...

When it was a PNG rather than actual fonts, the size and ratio was always correct, which was nice. Maybe these could be rendered to an HTML canvas instead...? The letters could be turned into svg sprites or something...? I haven’t fully thought it through but I don’t love how this happens with the words splitting up and the image squishing down:
<img width="657" alt="Screenshot 2024-01-13 at 3 42 04 PM" src="https://github.com/parkerdavis1/CCAM/assets/92223355/307f6af8-341b-4a58-b711-f7218f875d3d">

**Comment by garrett-laroy-johnson** [comment]
if it's a p5 canvas I got that lol

**Comment by parkerdavis1** [comment]
Also if you run into issues where the script doesn't run after navigation, it'll just need to be wrapped in an event listener: https://docs.astro.build/en/guides/view-transitions/#astropage-load

**Comment by garrett-laroy-johnson** [comment]
so far I'm using setTimeout() chains [this may be bad form???] and it's working a-ok

**Comment by garrett-laroy-johnson** [comment]
OK so switching between font classes works now. committing in a second. 

However, when I go to implement color changes, I'm not able to change the style of the div element from JS? getting a funny message : 

![image](https://github.com/parkerdavis1/CCAM/assets/6713092/40d78a0b-5219-4334-b839-f594dd8499f4)

(see code, line 187).

![image](https://github.com/parkerdavis1/CCAM/assets/6713092/0a918180-9b81-4274-9bb8-1b514fedc95a)

how could this be! astro black magic?

**Comment by parkerdavis1** [comment]
I’m pretty sure the `‘style’ does not exist` error is a typescript thing. It doesn’t actually break anything and seems to be more of a warning. The reason it wasn't working was the newColor variable was getting a random element from classes not the color array. Fixed that.

Also, I re-componentized the glitch title which got plowed over in the merges 😅. Its in `src/components/IndexGlitchTitle.astro`. We gotta try to remember to pull before committing and pushing.

**Comment by garrett-laroy-johnson** [comment]
amazing! thanks Parker -- 

my b on the pull thing -- I think I overrode that because I didn't know what was happening. 

Let's call this closed for now. Can add/change colors or change the speeds of change, @ioanbutiu
