### ISSUE TITLE
Footer p5 sketch

### ISSUE THREAD

**Issue by parkerdavis1** [parkerdavis1/CCAM#10]
I slapped in a killer p5 sketch in the footer. The p5 sketch from the original site needs to be refactored before it would work in its new context. I'm not mr. p5 so I think @garrett-laroy-johnson probably ought to do that. 

The (dope) gradient background and CCAM logo are HTML/SVG/CSS, outside of the p5 sketch, which I think would generally be good to do. The p5 can just take care of the swirlies. If we want the sketch to spill outside of the container we can talk about how we might go about doing that. 

![Screenshot 2024-01-06 at 12 01 12 PM](https://github.com/parkerdavis1/CCAM/assets/92223355/9fa383d0-8bb0-452f-a035-57d7490c75ee)

**Comment by parkerdavis1** [comment]
An idea: It would be tight if the refactor could make the sketch modular so that more control could be taken with when the p5 javascript gets loaded and handled on the webby. 
https://github.com/makinteract/p5js-wrapper

It makes the p5 syntax less friendly though, so def no big if not.

**Comment by garrett-laroy-johnson** [comment]
This looks rad — I can rewrite for sure. It doesn’t seem too complicated.

I’m in LA til tomorrow but will hopefully get to this and look at all these
incredible developments this week.

**Comment by garrett-laroy-johnson** [comment]
I committed a version with the particles working. 

I wonder can we change the background to solid color ? (light background when on dark mode, dark background on light mode)?

I'm having trouble importing a JSON file into the p5 sketch that stores the initial positions of the text outline. Any pointers here? Is this a modules thing?

**Comment by parkerdavis1** [comment]
Sweet @garrett-laroy-johnson ! You can import the JSON via the `import { points } from './points.json';` but the points.json as-is doesn't really work. The points will need to be recalculated for different sized screens...

**Comment by garrett-laroy-johnson** [comment]
Okay, then I think we need to draw the logo in p5.

**Comment by parkerdavis1** [comment]
Gotcha, sure that'd be fine. I thought separating the logo might be simpler and more robust/progressive-enhancement friendly but I didn't realize that the particles were moving in relation to the logo. Get it in there!!!

**Comment by garrett-laroy-johnson** [comment]
Honestly, now that I'm looking at this in the morning, I think let's leave it as is. It looks neat.

**Comment by parkerdavis1** [comment]
Right on. Yeah it looks good. A some point I might figure out how to make the script run when the user is closer to the footer and seeing it. Weirdly tricky...

This morning I made some major refactors that change how the script is loaded (prevents memory leaks) and make the sketch more modularized (for aesthetics?, even though the particle class is uglier now...).

**Comment by parkerdavis1** [comment]
Cool yeah got the sketch to run when it is visible with https://github.com/parkerdavis1/CCAM/commit/983770be70002fe664b7603d1ca491725915587b

**P5 FOOTER CLOSED**
