### ISSUE TITLE
Resources: tags, types

### ISSUE THREAD

**Issue by parkerdavis1** [parkerdavis1/CCAM#11]
Re: readme (@garrett-laroy-johnson I think using issues might be a better forum than the readme)

Right now there are only books as resources. I assume there will probably be online resources at some point so type still seems like a useful category (book, article, website, etc? any thoughts about what all the possibilities might be? maybe you don't care about this type of categorization though?). Adding tags in addition to type could be the way to go. They could easily be given colors from the color palate. Or the tags could be displayed in a different way than the type; having both be colored boxes might be visually confusing – @ioanbutiu might have thoughts on that.

**Comment by garrett-laroy-johnson** [comment]
Cool, let's keep "type". There is a google docs agenda for the gen~ group I may want to include, but also articles, etc.  Is there a place where types can be amended?

I think tags are key, so that if someone is interested in the Gen~ group, or generative sound, or psycoanalysis, they could look for resources tagged only with that tag. 

About display, that's a good thought.

**Comment by parkerdavis1** [comment]
@garrett-laroy-johnson  All the content schema is defined in the src/content/config.ts file

Mk, tags...tags...

So displaying tags, easy as hell, we just need to decide how things should look. Let me know.

Tag functionality: Do you want to be able to click a tag and see all resources that have that tag? 

This could be a UI filter on the resources page, similar to the program filter — though I worry about visual clutter since I imagine there'll be lots of different tags in total, tags galore

Maybe just clicking the tag itself on the individual resources would load up all the resources with that tag?

**Comment by parkerdavis1** [comment]
Also the only reason we might want to make our best attempt at predetermining the 'type' types ahead of time is to easily assign them consistent colors that automatically get applied for all future resources, otherwise it could just be a free-for-all 1000s of millions of resource types woohoooooooooooooooooooooo

**Comment by garrett-laroy-johnson** [comment]
I see the technical issue here. However, since we will be using names, places, and things for programming that hasn't been planned yet, it will not be possible to anticipate what all the tags will be right now. (see, for instance, Rhizome.org's tag list of people: https://rhizome.org/people/ way bigger project that's been going on way longer, but we want that space to expand without having to rewrite code.

is it possible to stock the tags with a large array of colors that new tags are assigned to by index? 
something like: 
```

var colorArray = ['#FF6633', '#FFB399', '#FF33FF', '#FFFF99', '#00B3E6', 
		  '#E6B333', '#3366E6', '#999966', '#99FF99', '#B34D4D',
		  '#80B300', '#809900', '#E6B3B3', '#6680B3', '#66991A', 
		  '#FF99E6', '#CCFF1A', '#FF1A66', '#E6331A', '#33FFCC',
		  '#66994D', '#B366CC', '#4D8000', '#B33300', '#CC80CC', 
		  '#66664D', '#991AFF', '#E666FF', '#4DB3FF', '#1AB399',
		  '#E666B3', '#33991A', '#CC9999', '#B3B31A', '#00E680', 
		  '#4D8066', '#809980', '#E6FF80', '#1AFF33', '#999933',
		  '#FF3380', '#CCCC00', '#66E64D', '#4D80CC', '#9900B3', 
		  '#E64D66', '#4DB380', '#FF4D4D', '#99E6E6', '#6666FF'];
```

but maybe much longer? Or, a random color is generated when a new tag is added?

**Comment by parkerdavis1** [comment]
## “Type” types
Re: “Type” types: sweet, thanks for that list. 

The design system as it is currently defined has ~5 colors + black + sand – so with these type types we’ll need some more colors. Different opacities, different hues, not sure. This all assumes we want to assign colors to the different resource types, giving the colors semantic meaning in relation to the types, which you know, is a choice. I'll just put in placeholder colors for now 👍 

## Tags
Re: tags – I’m not convinced that assigning tags semantic colors, or colors at all, is the best path. Things could start getting rainbow-y pretty fast. The open ended nature of the tags makes assigning semantic colors much more complex and probably not worth it, given the resource types (and program types) are already probably drawing from the same color palate and would further confuse the visual logic. Whatever you all decide though! If semantic tag colors are groovy, I am happy to puzzle over the least painful way of implementing them. 

I will work on setting up the tag logic and just display them as text. Hopefully at some point @ioanbutiu will have time to give these visual design things some consideration and @garrett-laroy-johnson you can tinker visually to your heart’s content.

**Comment by parkerdavis1** [comment]
Basic functioning tags and tag pages with 822664e4db342d1cc39ab6836d3428b24909b19a and 05a5ee0820a47f41cc155bd1090bc4f09d86ea20

Right now, all projects, programs, and resources need to have at least one tag. Let me know if this is not okay, it can be changed.

**Comment by parkerdavis1** [comment]
Some thought needs to be put into what metadata is shown for resources. Not everything will have an author and publish date. Tags would probably be good.

![Screen Shot 2024-01-20 at 16 28 36](https://github.com/parkerdavis1/CCAM/assets/92223355/8a3898e3-9c5c-46d6-9a93-06f858a7d34b)

**Comment by parkerdavis1** [comment]
Tags right now are case-sensitive. So 'art' is not the same tag as 'Art'...

**Comment by garrett-laroy-johnson** [comment]
Ok bet -- I'm adding some here as I add more resources, etc.

**Comment by parkerdavis1** [comment]
Took a cue from @ioanbutiu's new mocks to replace the card metadata altogether with tags 
![Screen Shot 2024-01-24 at 17 39 12](https://github.com/parkerdavis1/CCAM/assets/92223355/94ab119c-4420-42ef-b96f-8eb574e3a855)

**Comment by garrett-laroy-johnson** [comment]
Are we OK to delete the fake resources?

**Comment by parkerdavis1** [comment]
The only reason I can think of not to would be to see all of the resource type colors together, which could still use some work IMO. Otherwise get 'em out of there.

**Comment by garrett-laroy-johnson** [comment]
Cool -- I am asking because my mind is thinkin a bit more about making this public. See this issue about maybe moving this to a dev branch and starting to clean up main: https://github.com/parkerdavis1/CCAM/issues/24

**Comment by parkerdavis1** [comment]
This issue feels mostly resolved
