### ISSUE TITLE
program Date metadata

### ISSUE THREAD

**Issue by garrett-laroy-johnson** [parkerdavis1/CCAM#12]
following up on email thread. I think the three metadata categories make sense. 

presentationalDates - how the date is made legible to peeps
endDate - used for classifying "current" or "past"
pubDate - date the event becomes "published" or made visible. 

@parkerdavis1 could you add a filter for the last one? Maybe "if" there is no pub date, then it is assumed to be published?

**Comment by parkerdavis1** [comment]
Haha, you mean this issue? https://github.com/parkerdavis1/CCAM/issues/3

The pubDate is being used for ordering events right now so it, or something equivalent to it (a date that can be converted into a js date object), is required for each program. 

The pubDate could also control when things become visible on the site if that is something that is useful. I could set up a recurring build-hook that automatically triggers a rebuild of the site every day.

**Comment by garrett-laroy-johnson** [comment]
oops 0_o i thought this was an email. 

`The pubDate could also control when things become visible on the site if that is something that is useful. I could set up a recurring build-hook that automatically triggers a rebuild of the site every day.`

yes!!!

I'll close since the other is still open.

**Comment by parkerdavis1** [comment]
Lol, issue 3 was already closed and this one has more relevant info so lets OPEN'R BACK UP

**Comment by parkerdavis1** [comment]
pre-pubDate programs are filtered out in production build (but visible in development!) with 646ef0f32294a3503514b7376471d75703a6b8e8

I'll leave this issue open until after our meeting tomorrow in case there are any other metadata tweaks that might be needed.

**Comment by parkerdavis1** [comment]
In program metadata, draft (boolean) will determine if it is displayed on the index page, programs page, and prevent it from showing up in tags pages. Drafts still get generated and are viewable with a direct link.
