### ISSUE TITLE
gallery photo display for past programming?

### ISSUE THREAD

**Issue by garrett-laroy-johnson** [parkerdavis1/CCAM#13]
Can we add a gallery display to program? some component below the text. I know this can be a designer's nightmare to make look good, but photo documentation of programming is really essential for grant applications. 

On the programming side, possibly: the metadata can point to a directory, and images inside automatically are added? 

for instance:

![image](https://github.com/parkerdavis1/CCAM/assets/6713092/c68a9691-7c0a-4a59-b13f-abb2ab667b3f)

![image](https://github.com/parkerdavis1/CCAM/assets/6713092/631d5d71-857e-4607-a0c9-7ce654653648)

that's probably a lot of work. maybe there is a cleaner way to organize as well. componenitization, engage

**Comment by garrett-laroy-johnson** [comment]
I know that photo size will be an issue. What's best practice for having higher res photos available? have two versions? clicking on them leads to a high res version?

**Comment by parkerdavis1** [comment]
This won’t be a problem structurally. Do you have thoughts as far as how you want it to look? @garrett-laroy-johnson  or @ioanbutiu ?

I assume only some programs will have a gallery, correct?

The images would be compressed and optimized, no problem. If you want to make the high res photos available (via clicking on them) that would be possible as well, just let me know! 🚀

**Comment by garrett-laroy-johnson** [comment]
I guess my thought is that less clever is more clever. Maybe just a 3x grid ? 

Or, slightly more fancy: a 1x3 grid and then a "view more" link that goes to a grid page with documentation?

**Comment by garrett-laroy-johnson** [comment]
Also, there may be other kinds of accompanying documentation. For example,
at the informal informations event, we had a PDF of the zine.

**Comment by parkerdavis1** [comment]
Is this something that you would prefer to have a separate documentation page for, for each program? Or would a "below the fold" section of the existing pages suit you just as well? 

For a "many photos" situation I'm thinking of just incorporating this into the pages: https://www.lightgalleryjs.com

Maybe it can handle youtube videos as well. If not, I already have a PERF-FOCUSED youtube component in the project that is extremely simple to put anywhere in a markdown file (mdx file specifically)

How do you imagine displaying the PDF? A link to the download...or something else? 

If you can imagine some sort of standard practice and display (eg. we will always want the main text, and then the gallery, and then something at the end, etc) that would work for all of the pages, these things could be built into the template of the page and then be configured in the frontmatter. 

Alternatively, there could just be a few different components set up for you (gallery component, youtube component, pdf component(..?)) that you could insert into the markdown (mdx) and arrange and configure them as you see fit for each case. 

Anything is possible! You just tell me what is desired with as much detail as possible and I'll try to come up with the best way to make it happen.

**Comment by parkerdavis1** [comment]
Also, these markdown files can have html and scripts and everything you might put in an eleventy page file and it will work the same in most cases.

...and thinking further down the line once everything is all set to launch, I haven't *quite* used Sanity before but I have a vague notion that it might allow for custom component type things to be incorporated into its workflow. I think you, Garrett, can handle importing components into mdx files and getting it all set, but Sanity could help put some guardrails up if anyone else is trying to get in there and edit content, create and arrange photo galleries etc.

**Comment by garrett-laroy-johnson** [comment]
Right on yeah then apart from a default gallery setup we can rely on MD to
handle embeds etc and other one-off media.

**Comment by garrett-laroy-johnson** [comment]
Light gallery looks perfectly perfect. No need to reinvent the wheel.

I think “below the fold” is fine for now. We can avoid too much sprawl to
separate pages for now.

Let’s nix making a component for pdf (they can just be links to separate
pages.) if it’s a special case where it needs embed I can do that as an
iFrame in the markdown.

“
If you can imagine some sort of standard practice and display (eg. we will
always want the main text, and then the gallery, and then something at the
end, etc) that would work for all of the pages, these things could be built
into the template of the page and then be configured in the frontmatter.”

This sounds like the ticket for now!!

**Comment by parkerdavis1** [comment]
There is a barebones grid gallery now: see https://ccam-staging.netlify.app/programs/23-10-weird-dreams-vernissage/

It works exactly like you suggested: you include a gallery in the front matter with the name of the folder of images, which should be in the `src/content/programs/images/` directory

**Comment by parkerdavis1** [comment]
Lighthouse lightgallery activated. Photo gallery folders now need to live in the public folder `public/assets/images/*` in order to make the full resolution images available. 

![Screen Shot 2024-01-19 at 17 27 11](https://github.com/parkerdavis1/CCAM/assets/92223355/8551b520-5818-4e8d-9646-84289f2fd85f)

![Screen Shot 2024-01-19 at 17 27 19](https://github.com/parkerdavis1/CCAM/assets/92223355/4e15655a-b166-4fa1-a9ba-62280e5e5ad1)
