### ISSUE TITLE
Projects fleshing out

### ISSUE THREAD

**Issue by parkerdavis1** [parkerdavis1/CCAM#14]
Projects

From email:
* projects
    * similar to programs, but are ongoing streams of work that is research, artistic production, or a mix of both. \
    * projects may contribute to programs 
    * projects page enumerates these instances
    * project pages template might differ from program pages. 
        * they might display/enumerate relevant (tagged?) program instances
        * they might have some external people associated with them that should be named or linked to.

This sounds cool but needs to be fully fleshed out / I need to understand it more fully before it is implemented. 

"projects may contribute to programs" Sounds like both the programs and projects will link to each other; can you tell me more about how you envision this? 
Assumptions: 
- programs can have a simple text link  right at the top "Part of the {{rad}} project"
- Project pages will have a grid of, "Associated Programs(??? or something better...)" -  These could look just like the 'cards' on the program page, or they could be smaller and more text based, closer to resources cards, or? Will there need to be a separation of Upcoming and Past associated programs?
- Are there other requirements I'm missing?

"they might have some external people associated with them that should be named or linked to."
- How do you envision the associated people element looking? This could be text/link, or something else...a photo perhaps...etc. Do you want people's About pages to also link to their associated projects? How do you envision that looking?

**Comment by garrett-laroy-johnson** [comment]
Thanks for helping me to think through this! Essentially the headline is that project pages are for a CCAM initiative that guides programming (and potentially residencies, commissions, book publications, etc.). 

Practically, CCAM might need to use a project page to aggregate materials in pursuit of programming.

This is not a bad model: https://www.c-p-t.org/projects/time-shores 

we might speculate about the metadata for this page: 

projectTrack: "planetary technologies"
conveners: 
- foo
- fee
tags: 
- hoo
- loo
- soo
events: 
- oceanfront.astro (??)
- archeology.astro (??) // I don't really know if this is how this would work. 
description:  
- lorem ipsum
- lorem ipsum 
imgs: 
- /assets/img/shore1.png
- /assets/img/shore2.png


I think that is a good baseline. I would add a few more data:

participants: 
- john doe
- steve dave
- cindy loo
resources: 
- anthropocene-laboratory.astro (?? again, not sure how to reference these components). 

Gonna comment inline on other questions: 

``` programs can have a simple text link right at the top "Part of the {{rad}} project" ```
Yes! I think that would be great to link back to the project from a program page. Some events won't have a host project.


    ``Project pages will have a grid of, "Associated Programs(??? or something better...)" - These could look just like the 'cards' on the program page, or they could be smaller and more text based, closer to resources cards, or? Will there need to be a separation of Upcoming and Past associated programs?
```
We can try starting with the cards from the program page. They might be a bit too bulky? I think the inclination to do something more text based or like the resource card is smart.

**Comment by parkerdavis1** [comment]
Haha, the specifics of the example metadata are only confusing me more. 

project track: this is just the project name...right?

conveners: I don’t know what this means. People associated with it? How does this relate to participants?

tags: How will tags assigned to Projects function in the context of the website...? Like...a project could have [Gen~] tag... and... then what? Does it need to do anything programmatically other than be visible on the project page? Ooohhhh Okay, so the page for the [Gen~] tag will have all PROJECTS, PROGRAMS, AAAAND RESOURCES associated with that tag listed on the tag page. okay okay okay okay got it. cool. Do I have this right?

events: associated events (PROGRAMS, right?) will not need to be explicitly listed via the project frontmatter. The programs themselves will be tagged with the project tag, then they can automatically populate the project page, because they have the project tag associated with them. Unless you want more fine-grained control over what programs show up on a project page. Will listing them all, or the most recent (n) suffice? Or do you want to define these things manually?

These conceptual requirements gathering conversations might be easier and faster sorted out using human voices rather than text.
