### ISSUE TITLE
summary preview 

### ISSUE THREAD

**Issue by garrett-laroy-johnson** [parkerdavis1/CCAM#15]
![image](https://github.com/parkerdavis1/CCAM/assets/6713092/5e0e938b-c0c7-472c-a1e1-b3bd5e5dcb2d)

could we replace this description with " Nomadically based in Chicago, CCAM is an artist-run platform at the nexus of art, technology, and contemporary thought. " 

Not sure where this might be hiding!

**Comment by parkerdavis1** [comment]
Donezo. For future reference when you see some text you want to edit: in VS Code, `Command+ shift+ F` search the whole project for text "Astro description" and you'll see it is in the head meta data in the Base layout file. 

There is plenty of meta data finessing that can be done. Adding social share images and dynamic descriptions for each page, etc.
