### ISSUE TITLE
Tags

### ISSUE THREAD

**Issue by parkerdavis1** [parkerdavis1/CCAM#16]
Basic tags are implemented. 

Design decisions:
- How tags are displayed on Programs, Projects, and Resources
	- boxes? colors? hashtags? dashed underlines?
- Tags pages design
	- individual tag pages
	- all tags page

Contributors, participants, conveners will enter the tagiverse but be displayed differently

**Comment by ioanbutiu** [comment]
@parkerdavis1 @garrett-laroy-johnson did a quick pass at the tag page, which i'm calling "search" because it's more readily apparent what that is. Also put it in the nav and moved instagram link to footer. Let me know what you think, it's pretty basic : https://www.figma.com/file/NkOPmhCvYwwuBzdrXYHJCp/CCAM?type=design&node-id=741-1084&mode=design&t=iSeaWj8p72PEILsS-4

**Comment by parkerdavis1** [comment]
I like it. Thanks for the speedy mocks!

Clarifications:
1. Projects and Programs would also need to be displayed. Converting their data and images into a “resources style” rectangle is straightforward enough. @ioanbutiu  How might we differentiate between Resources v Programs v Projects results in the tag view? 
2. I wonder what the best way to display this on mobile would be.
3. I wonder how the tag list would feel on the right side with the same proportions of the Nav box. I’m sure you tried this. Maybe it’d feel lopsided. 
4. Calling it search without an actual search bar feels a little weird. Given the number of hours I’ve put i already, I’m not chomping at the bit to implement a search before launch. I think incorporating https://pagefind.app/ with some hints from https://astro-cactus.chriswilliams.dev/ would be relatively simple if someone wanted to do that later. Hell, I’d probably be psyched to do it later, I would like to prioritize getting an “MVP” (minimum viable product) “Shipped” though ;) Do you guys feel gross now? Nice.

**Comment by garrett-laroy-johnson** [comment]
good Q's parkler. i'll weigh in , if only to keep the ball moving. 

> 
>     Projects and Programs would also need to be displayed. Converting their data and images into a “resources style” rectangle is straightforward enough. @ioanbutiu How might we differentiate between Resources v Programs v Projects results in the tag view?

true ya this should showcase all those as well. It makes sense to me that they all are shoe-horned into the "resource" look that Ioan shows here, but I'll give the opportunity for him to suggest something else if that's desirable.

>     I wonder what the best way to display this on mobile would be.

mmhmm.

>     I wonder how the tag list would feel on the right side with the same proportions of the Nav box. I’m sure you tried this. Maybe it’d feel lopsided.

could be interesting to try out

>     Calling it search without an actual search bar feels a little weird. Given the number of hours I’ve put i already, I’m not chomping at the bit to implement a search before launch. I think incorporating https://pagefind.app/ with some hints from https://astro-cactus.chriswilliams.dev/ would be relatively simple if someone wanted to do that later. Hell, I’d probably be psyched to do it later, I would like to prioritize getting an “MVP” (minimum viable product) “Shipped” though ;) Do you guys feel gross now? Nice.

🙃 

I'm ok with this being slightly confused (no search bar capabilities) for a bit if we intend to build this out later. I think this mockup is close to our MVP (pronounced "em vee pee") if we can show projects + programs too. 

Page find looks neat -- maybe i'll add that to my course wbsites... 

full ship ahead!

**Comment by parkerdavis1** [comment]
Oh wow, using the resource template the freaking resource 'type' tag could just say program and project. I'm a freaking genius.

**Comment by parkerdavis1** [comment]
Took a pass at the `Search` tagiverse page.

Tags on right side, hot or not?

![Screen Shot 2024-01-24 at 17 31 27](https://github.com/parkerdavis1/CCAM/assets/92223355/d93aada8-e715-46b0-97cf-30ff12f38b9f)

**Comment by parkerdavis1** [comment]
I haven't yet put the bracket-style theme switcher in yet just because I haven't gotten around to it. I just thought about it and having the instagram link next to a [ ] thing is reminiscent of the nav things up top and might be *very slightly* confusing that the Instagram regular link and [🌖] theme switcher are two different things. nbd tho

**Comment by garrett-laroy-johnson** [comment]
> Took a pass at the `Search` tagiverse page.
> 
> 
> 
> Tags on right side, hot or not?
> 
> 
> 
> ![Screen Shot 2024-01-24 at 17 31 27](https://github.com/parkerdavis1/CCAM/assets/92223355/d93aada8-e715-46b0-97cf-30ff12f38b9f)
> 
> 

Spatially this makes a lot of sense to me.

**Comment by garrett-laroy-johnson** [comment]
I also really dig the view on mobile. Simple and easy to understand, to my eyes. 

![image](https://github.com/parkerdavis1/CCAM/assets/6713092/7f972599-b883-4dc6-9d21-2d58dfe38423)

**Comment by parkerdavis1** [comment]
This issue feels mostly resolved
