### ISSUE TITLE
Misc color decisions

### ISSUE THREAD

**Issue by parkerdavis1** [parkerdavis1/CCAM#19]
- Color coding of Upcoming/Ongoing/Past
	- upcoming/ongoing light with border and past black background?
- Meta theme-color (safari/ios/android top bar coloring) (currently whatever the background color is)
	- file: `src/styles/global.css` property: `--meta-background`
- Need to decide on resource type semantic colors (https://github.com/parkerdavis1/CCAM/issues/11)
	- website
	- image
	- codebase
	- video embed
	- book
	- article
	- magazine
	- periodical
	- organization  
	and maybe a generic catchall:
	- link
- Contact dialog backdrop color (currently see-through black)
- Scrollbar color (currently purple on light, green on dark)
- Highlight color (currently green)
- Cursor carrot color (currently orange)

**Comment by parkerdavis1** [comment]
Just so you guys know, this is an option...

![Jan-30-2024 15-52-28](https://github.com/parkerdavis1/CCAM/assets/92223355/ec99e867-be46-4104-857d-90aab77bcb2e)

There could be a secret button somewhere that activates terrible blinky mode.

**Comment by garrett-laroy-johnson** [comment]
Aww jeeze this makes me wish I used safari...

**Comment by garrett-laroy-johnson** [comment]
I also picked up the color palette for insta as people saw. I guess we are locked in to the 2024 rebrand colors <3

**Comment by parkerdavis1** [comment]
At this point, the colors that might benefit from some tweaking are the resource semantic colors but they feel pretty fine to me so no need to have this issue lingering...
