### ISSUE TITLE
Placeholder text and images

### ISSUE THREAD

**Issue by parkerdavis1** [parkerdavis1/CCAM#21]
- [x] Home page: 2 images
- [x] About page: 2 images (+captions?), higher res headshots
- [x] Bio pages: Bios
- [x] photo gallery, mosaic, etc. display for Program pages

**Comment by garrett-laroy-johnson** [comment]
I've added some higher res headshots, not sure how to switch those out (is this some component magic?) 

same with "space" photos. I am doubtful that my photo is going to look good on the page. It's nice because there's a lot of people, but the space is very dark and has a strong AF red carpet, which is not the vibe. I tried to color correct, but I'm bad at that.

**Comment by parkerdavis1** [comment]
It's an Astro/Vite thing, you just have to import the image in the component script (the top --- frontmatter-looking area --- with the build time javascript). Then referencing it in the <Image /> component like you did will work.

https://docs.astro.build/en/guides/images/#images-in-astro-files

**Comment by parkerdavis1** [comment]
> "I added "higher res" photos for me and Kim. Waiting on Muindi. Do we need higher still??? I need a new headshot anyhow...
> 
> I also added a "workshop" photo that I tried to do some color correction on (poorly). Maybe we can try subbing this for the "space" photos?
> 
> I can try to find someone else to edit the photo too, or maybe there is a different photo...."

These new ones look fine to me. No ultra high res needed. The old ones were just a little small and compressed looking.

**Comment by garrett-laroy-johnson** [comment]
Added a  Muindi hi res image too. Thanks!

**Comment by garrett-laroy-johnson** [comment]
This is sorted. I removed (commented out) the last image in About. I'm not sure it makes sense to repeat these. Looking for another photo from programming last year to use...
