### ISSUE TITLE
generative cards for people without photos?? 

### ISSUE THREAD

**Issue by garrett-laroy-johnson** [parkerdavis1/CCAM#22]
@ioanbutiu had the nice idea to generate program cards people who don't have images. That seems smart "cover your butt" move, but also like it'd look real neat. 

![image](https://github.com/parkerdavis1/CCAM/assets/6713092/92efe8f6-3434-4008-8828-5587154318f8)

I can write a p5 sketch that creates these generatively. 

@parkerdavis1 are either of these feasible: 

- embed a p5 Canvas in the space where the image would be
- I could render 15 or more as .jpg files and a person card w.o image could cycle through them or grab them randomly

**Comment by parkerdavis1** [comment]
Yeah, I liked this idea too!

I would really prefer not to embed p5 canvases for this use case unless you want to do some fancy animations that p5 enables. 

I was thinking along the lines of generating them dynamically at build time. I didn’t find a premade library for making this super easy. If p5 could somehow be run "server side" to generate the things at build time that'd be tight but I'm not sure if that is possible...?

Pre-rendering a bunch and randomly choosing one would be the simplest. (“M” “V” “P”! “M” ”V” “P”!)

Making these randomly generated things “stick” to the people or whatever they are attached to would require bringing in a database for dynamic data persistence or manually assigning them though.

**Comment by garrett-laroy-johnson** [comment]
Word , it’s no problem to generate a few different ones. P5 is possible in
node context, but that feels like overkill.

@ioan can you say a bit about how you’re made the  current images? I can
try to wing it in the meantime.

**Comment by garrett-laroy-johnson** [comment]
I added 20 images to /src/assets/images -- not sure where is convenient for this.

**Comment by parkerdavis1** [comment]
They look cool 😎
