### ISSUE TITLE
Add a [view all] button under the program listings on home page

### ISSUE THREAD

**Issue by garrett-laroy-johnson** [parkerdavis1/CCAM#23]
I really like the program listings on the home labs of course, but I wonder if we can add a [view all] button under it so people don't think those are the *only* things coming up. 
![image](https://github.com/parkerdavis1/CCAM/assets/6713092/b9d30fcb-8580-4949-acca-0e35d2b573ab)

**Comment by garrett-laroy-johnson** [comment]
Copy paste this thing and swap link:

![image](https://github.com/parkerdavis1/CCAM/assets/6713092/042a8737-f5a1-4a1f-8384-7ada583809ab)

**Comment by parkerdavis1** [comment]
Just tacking a [View All] after the programs would be confusing, view all what? [View All Programs]? 

Maybe similar to Resources heading on the homepage, adding a small Programs heading with a `View All` button next to it above the programs?

**Comment by parkerdavis1** [comment]
Works pretty well. Thumbs up?

Desktop
![Screen Shot 2024-01-25 at 10 55 02](https://github.com/parkerdavis1/CCAM/assets/92223355/1f1806c1-77fa-406f-aa0e-e5783f36cbc1)

Mobile
![Screen Shot 2024-01-25 at 10 55 20](https://github.com/parkerdavis1/CCAM/assets/92223355/9179c70d-32c4-491e-8742-6aff0201840c)

**Comment by garrett-laroy-johnson** [comment]
thank you! perfect :)
