### ISSUE TITLE
Tag conventions / people vs other

### ISSUE THREAD

**Issue by parkerdavis1** [parkerdavis1/CCAM#30]
Sensible tag convention would be names capitalized, everything else all lowercase. There is some inconsistency and duplication happening at the moment in the tagiverse. 

People could also be separated out into their own separate tagiverse that is displayed separate from others. Design question.

**Comment by parkerdavis1** [comment]
Another option: all tags could be automatically lowercased to prevent any duplication and confusion.

**Comment by parkerdavis1** [comment]
tags I've noticed that probably want resolution: 
gen~ vs gen~ working group
diysynth vs synthdiy

**Comment by garrett-laroy-johnson** [comment]
Thanks, yea, lemme bring my more focused eyes to this over a cup of coffee soon. Ostensibly -- gen~ and gen~ working group are different, but, if I follow your drift, maybe the point of the convention is to use fewer tags that more strategically link different pages etc. 

ring a ding ding

**Comment by parkerdavis1** [comment]
for sure they may warrant different tags but in that case all of the gen~ working group things probably should *also* have the gen~ tag is all I'm sayin'

**Comment by garrett-laroy-johnson** [comment]
👍

**Comment by garrett-laroy-johnson** [comment]
> Another option: all tags could be automatically lowercased to prevent any duplication and confusion.
> 
> ![Screen Shot 2024-02-03 at 08 03 16](https://private-user-images.githubusercontent.com/92223355/302043588-2ddf5f3c-d049-477a-835c-057c18bebac4.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDg2MzUxMjQsIm5iZiI6MTcwODYzNDgyNCwicGF0aCI6Ii85MjIyMzM1NS8zMDIwNDM1ODgtMmRkZjVmM2MtZDA0OS00NzdhLTgzNWMtMDU3YzE4YmViYWM0LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAyMjIlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMjIyVDIwNDcwNFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWE2ZGQ3YzM4MDY1YzJmMThmZDA5OTk4ODhjZDAyNGE0MDI0ZjFhOGY5MDlmYTRmYzBmYjUzNzBiYjg4MTYwMWEmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.0--jIFot3YGokRgUBDlZK450oOYii0mA86qm7mOzUc8)

It is implemented this way, no? I like it this way :)

**Comment by parkerdavis1** [comment]
It is! (it wasn't when I made that comment ;))

I added `gen~` to the `gen~ working group` things, changed the one `synthdiy` to `diysynth` and auto-lowercase reduces surface area for duplication errors so I think this is worthy of CLOSURE
