### ISSUE TITLE
Drafts visible via sitemap

### ISSUE THREAD

**Issue by parkerdavis1** [parkerdavis1/CCAM#31]
I’m adding sitemaps, robots.txt metadata stuff. Minor hiccup with the way drafts work. 

All the programs with draft set to true are built and viewable via direct link, but are not linked to anywhere on the site. As I understand it, this is desirable.

However, draft programs will be included with the sitemap. This means if someone decided to look through the sitemap, like a search engine crawler, they will be able to see the draft pages.

This probably isn’t a big deal but you should be aware of it. Draft things *could* show up in search results, especially if they sit in drafts for a very long time. If you definitely wanted draft pages to be ‘secure’ I could make it so they are not built, but then you won’t be able to share them with people via direct link. 

Is this a problem?

**Comment by garrett-laroy-johnson** [comment]
I don't think this is a problem.

For clarity, does this include dev branch?

**Comment by parkerdavis1** [comment]
Huh, yeah, interesting question! Yeah I changed some things around so that the dev branch deploys *shouldn’t* be indexed by crawlers. (“Where lies the strangling fruit that came from the hand of the sinner I shall bring forth the seeds of the dead...”)

ccam-staging.netlify.app is DEAD

LONG LIVE dev--ccamworldlive.netlify.app

**Comment by garrett-laroy-johnson** [comment]
👏

**Comment by garrett-laroy-johnson** [comment]
hey, Annihilation is a good book ehh?

**Comment by parkerdavis1** [comment]
I liked how menacing the river dolphins were
