### ISSUE TITLE
Person social links don't link to anything

### ISSUE THREAD

**Issue by parkerdavis1** [parkerdavis1/CCAM#39]
Social urls need to be inputted for all people.

**Comment by garrett-laroy-johnson** [comment]
I can do this for everyone that has one, but some folks won't have. 

is there a reason we can't have them show up like this when a person has no social?

![image](https://github.com/parkerdavis1/CCAM/assets/6713092/c1f03620-03b4-4c67-87ff-1ba1cb59de73)

**Comment by parkerdavis1** [comment]
Yeah sorry, I mean: right now a lot of people have social handles inputted, so they do show up on the page. If they have a handle inputted, they need to also have a URL attached to it, otherwise they link to nothing. This allows people to link to whatever social they want to. Not just instagram or whatever.

**Comment by garrett-laroy-johnson** [comment]
ohhhhhh I just saw this. makes sense now. Can do.

**Comment by garrett-laroy-johnson** [comment]
I did it!
