### ISSUE TITLE
Added Hidden Gallery 🎉🎉🎉🎉

### ISSUE THREAD

**Issue by parkerdavis1** [parkerdavis1/CCAM#52]
Pages with big ass galleries are SLUGGISH NO MORE

The gallery now will display the first few photos, then you click show me more and THEN it loads those mothers. I know this is super basic web design stuff, but man, I feel like an elite hacker the way I made that work. 

Any suggestions on the design???

Also definitely test it out on all your devices. This is a new technique for me. If it doesn’t work in some settings let me know.

Pages with galleries:

https://dev--ccamworldlive.netlify.app/programs/24-2-15-i-want-an-ai-for-president/

https://dev--ccamworldlive.netlify.app/programs/23-10-weird-dreams-vernissage/

https://dev--ccamworldlive.netlify.app/programs/23-9-all-watched-over/

Want a @garrett-laroy-johnson sign off before pushing to production

**Comment by garrett-laroy-johnson** [comment]
Yayayayaya hell ya parksy u rocking it
