### ISSUE TITLE
Swirly LOGO?

### ISSUE THREAD

**Issue by parkerdavis1** [parkerdavis1/CCAM#57]
@garrett-laroy-johnson Cheggit, this good?

![Screen Shot 2024-02-23 at 16 17 17](https://github.com/parkerdavis1/CCAM/assets/92223355/7391de26-ea1f-4051-9636-8a6142111e5a)

https://dev--ccamworldlive.netlify.app/

Note to self: I need to go through and make sure all these animations disable when "user prefers reduced motion"

**Comment by garrett-laroy-johnson** [comment]
if you get rid of this I'm pulling the plug

it's TOOOO sick

**Comment by garrett-laroy-johnson** [comment]
where is the p5 code? I might change a couple things to encourage the
particles to go right

**Comment by garrett-laroy-johnson** [comment]
true......



the canvas adapts to the div / display size, no? could put some code in
there to trigger the right pull *if* we know it's in desktop width.

**Comment by parkerdavis1** [comment]
word, yeah the width breakpoint is 640px

**Comment by parkerdavis1** [comment]
Okay there are several sick options for the swirlies

1. contain all swirls the way they were. Classy. Classic.
![absolute-contain](https://github.com/parkerdavis1/CCAM/assets/92223355/78376e10-08d2-4be6-b7df-71d21dff4c6a)

2. let only the top swirl break out and it scrolls away as you scroll, the way you might expect
![absolute-spill](https://github.com/parkerdavis1/CCAM/assets/92223355/800a6b01-4311-4d4e-b6da-b6ff3e78727f)

3. same as above but both the header and footer swirlies do it! (no preview, would require slightly more involved refactoring)

4. the top swirl breaks out *and* is a static background that sticks with you as you scroll (currently active on https://dev--ccamworldlive.netlify.app/)
![fixed-spill](https://github.com/parkerdavis1/CCAM/assets/92223355/ef9f8519-b5bb-4a46-a4e4-f5cdcd8e139f)


The question becomes, is this too much swirlyness? Is CCAM **that** swirly? In the case of 4, I think we’ve need to get rid of the bottom footer logo altogether because it would just be too much swirl. But the swirls breaking out of their confines is pretty cool (of course this was the sickness from your original site @garrett-laroy-johnson). I would probably rank the options best to worst, 3, 4, 1, 2.

**Comment by parkerdavis1** [comment]
Okay nvm option 4 is buggy on mobile, option 3 is probably the way to go?

**Comment by parkerdavis1** [comment]
lol, yeah this design stuff can drive me crazy...

Is the swirl breaking out of the boxes too distracting?

![Screen Shot 2024-02-24 at 14 34 48](https://github.com/parkerdavis1/CCAM/assets/92223355/d9933030-933e-44d6-9561-f5574cd59fd8)

Making the swirl break out of the box on the bottom is a bit more complicated it turns out. But having both breaking out of the box on every page top and bottom. Its pretty swirly. Maybe it's too much swirl. 

![Screen Shot 2024-02-24 at 14 40 10](https://github.com/parkerdavis1/CCAM/assets/92223355/e5f6696e-d2b0-4d78-8e73-d5f5940b592d)


Related side-note: there is no way to have the swirl to break into the email signup box, as you can see above, because of the way the brackets work. 


Maybe just generally having both swirls in any configuration is too much swirl?

😬

**Comment by parkerdavis1** [comment]
Maybe the contained swirl was the way to go all along...

I could see the 'space' photo area on the index page being a spill out animation area of some kind at some point. Then it would only be on the home page, not *every* page.

**Comment by parkerdavis1** [comment]
Cool. I added some background opacity to it. Very tasteful breaking out of the box. 🥂
Live on site with PR https://github.com/parkerdavis1/CCAM/pull/58
