### ISSUE TITLE
Favicon update

### ISSUE THREAD

**Issue by ioanbutiu** [parkerdavis1/CCAM#6]
@garrett-laroy-johnson @parkerdavis1 how do we feel about this favicon?

![CleanShot 2024-01-02 at 16 19 58@2x](https://github.com/parkerdavis1/CCAM/assets/36743419/27c3dd7e-96a5-454f-b6a3-d561193636da)

**Comment by garrett-laroy-johnson** [comment]
I think this works great with the site language! It shows up a bit dark in
my "dark mode" browser, so I wonder about doing this on a white background,
or using a white outline around the characters?

[image: image.png]

**Comment by parkerdavis1** [comment]
I can dig it. Instead of adding a background to deal with dark mode, you can add media queries to favicon links to swap a light and dark favicon https://www.epicweb.dev/tips/responsive-favicons

**Comment by parkerdavis1** [comment]
Reopened as a reminder to implement the dark mode favicon

**Comment by garrett-laroy-johnson** [comment]
oh my b 🌾

**Comment by parkerdavis1** [comment]
I just put in some media-responsive icons but for some reason it is buggy on Firefox... Not sure why... e702d0f2c91910a4686df0c792acb61e91c80283

**Comment by garrett-laroy-johnson** [comment]
![image](https://github.com/parkerdavis1/CCAM/assets/6713092/c1577219-60a9-4fe6-b671-d9479cc3066b)
got a positive result on firefox to night

**Comment by parkerdavis1** [comment]
Swaieet lets CLOSE this sucker
