### ISSUE TITLE
program page ordering?

### ISSUE THREAD

**Issue by garrett-laroy-johnson** [parkerdavis1/CCAM#65]
not an issue more of a question, maybe turning into an issue.

@parkerdavis1 can you remind me how program page is ordering programs? It's something to do with pubDate frontmatter, but it seems it's putting later pubDates first. Is that correct?

**Comment by parkerdavis1** [comment]
It is set to be sorted by pubDate, but the pubDate for a lot of events is the same date 2024-01-01, so I’m not really sure how it is ordering things right now actually. Some fallback like file created date or, I don’t know. 

Maybe it should be ordered by endDate instead, which for most one day events would be the day of the event...I think this might be more intuitive and sensible...? 

Not sure where we should put ‘ongoing’ events in the ordering of things, that’s a question for you.

**Comment by parkerdavis1** [comment]
@garrett-laroy-johnson programs are ordered by endDate now, with 'ongoing' being treated as later than everything else.

**Comment by garrett-laroy-johnson** [comment]
:clap: thank u!!! ok that makes sense.

I'll change the pubDate for future events.

**Comment by parkerdavis1** [comment]
Ur welcome!!! just so we're crystal the pubDate only determines when a program is "published" now. All ordering is by endDate. 👍
