### ISSUE TITLE
Tagiverse Saga continues

### ISSUE THREAD

**Issue by garrett-laroy-johnson** [parkerdavis1/CCAM#66]
@parkerdavis1 , some time ago you suggested displaying associated resources in the Projects. Or maybe a more extreme version, which was to display all things everywhere lol. 

Would it be easy to add a component to projects that would display the associated resources? 

I am thinking because we are gearing up a reading group and it would make sense to embed the readings as resources.

**Comment by parkerdavis1** [comment]
It would be easy enough. Many questions follow.

Where do you want it to be? 
 
It could be similar structure to “People”, and placed above or below “People” but always after all of the text. 

It could be a component that can be placed within the text. This would also mean it would maybe have to be text width (a little narrower on wide screens).
<img width="1035" alt="Screenshot 2024-03-02 at 4 38 04 PM" src="https://github.com/parkerdavis1/CCAM/assets/92223355/c337f5bf-da9f-4bd4-9d31-fa65ec9f91c5">

Or something not yet dreamed up...!

**Comment by garrett-laroy-johnson** [comment]
I think in terms of display the screenshot works well for me mentally. 

if it's all the same, maybe we could implement this for both Projects and Programs. We could include a frontmatter boolean to toggle it on and off? e.g.
```

---
displayResources: true
---
```
For implementation, is it possible to designate a #tag that autocollects the resources on build? (is that what you mean when you envision mirroring the people structure?)

**Comment by parkerdavis1** [comment]
I'm thinking something like
```
---
displayResources: diysynth
---
```

and it displays resources with the given tag. If it is blank or undefined, resources are not displayed. 

In this case, it would be normal full width above or below "People" (if they are present)

**Comment by parkerdavis1** [comment]
and would have a generic heading of "Resources" or do you want something customizable (ala people)

**Comment by garrett-laroy-johnson** [comment]
Word -- that works! let's do the generic "resources" header. <3

**Comment by parkerdavis1** [comment]
So resources are ready to add to Programs. See: https://dev--ccamworldlive.netlify.app/programs/24-3-17-hackathon/
<img width="1436" alt="Screenshot 2024-03-02 at 5 52 27 PM" src="https://github.com/parkerdavis1/CCAM/assets/92223355/370383f4-92ab-41c8-96f9-fab51f228a1c">

And apparently I already implemented this for Projects. You just need to tag resources with the associated `ProjectId`.

**Comment by garrett-laroy-johnson** [comment]
🥳🥳🥳
