### ISSUE TITLE
Cursor Party

### ISSUE THREAD

**Issue by parkerdavis1** [parkerdavis1/CCAM#74]
I just put this on my site and it is very easy, and fun. Seems like a perfect fit for the CCAM DIGITAL ARTS WEBSITE.

https://blog.partykit.io/posts/cursor-party

https://github.com/partykit/cursor-party

Things can be modified and styled. Any ideas of fun ways to customize and CCAMify (styling cursors, different colors shapes...chat can be disabled if that is a concern)?

**Comment by garrett-laroy-johnson** [comment]
Wow, with one click?? I guess they are running a server somewhere? Yes
let’s do it !!!

**Comment by garrett-laroy-johnson** [comment]
*one line of code

Ima bit at wit's end 🫠

**Comment by parkerdavis1** [comment]
You got it Gar!

Yeah, they give you the server starter code to configure then you can deploy it to their servers then you hook it up to your site with that script. Its not *just* slappin' a script in there but pretty awesome how easy it is.

**Comment by parkerdavis1** [comment]
Its up on the [dev branch](https://dev--ccamworldlive.netlify.app) – merge that sucker into main to go live!

**Comment by parkerdavis1** [comment]
baaah, this isn't playing nice with astro's page-transition/javascript routing stuff... hmm

**Comment by parkerdavis1** [comment]
Shoot. I don't think this is going to work with how the site is currently setup and I don't think the trade off for changing it is *quite* worth it. False alarm!!! PARTY'S OVER
