### ISSUE TITLE
google preview

### ISSUE THREAD

**Issue by garrett-laroy-johnson** [parkerdavis1/CCAM#77]
is there a reason our favicon doesn't show up for google preview? 

![image](https://github.com/parkerdavis1/CCAM/assets/6713092/3f54614b-2c19-4a7e-a118-9f7a7e3ad539)

**Comment by parkerdavis1** [comment]
Good question!

**Comment by parkerdavis1** [comment]
hmmm, this makes me think: no.

<img width="647" alt="Screenshot 2024-03-14 at 6 12 25 AM" src="https://github.com/parkerdavis1/CCAM/assets/92223355/c20132de-7889-479a-8ed5-a733068519e4">


but I'll look into it

**Comment by garrett-laroy-johnson** [comment]
Oh funny ! Maybe it takes days for the favicon to show up for google ?

**Comment by parkerdavis1** [comment]
I changed some things around that *maybe* will help google deal better. We'll see.

**Comment by garrett-laroy-johnson** [comment]
Thanks Park- let's mark this closed then.
