### ISSUE TITLE
Org Logos Transparent Backgrounds

### ISSUE THREAD

**Issue by parkerdavis1** [parkerdavis1/CCAM#84]
@garrett-laroy-johnson 
The org logos have white text and transparent backgrounds which makes them illegible in light mode. 
https://dev--ccamworldlive.netlify.app/programs/24-4-05-we-dont-know-what-a-cinema-can-do-sound-video/

Easy fix: get logos with backgrounds

Another fix: If you're able to get the logos as SVGs, I could make it so they dynamically adapt to the background. (Black fill on light, White fill on dark)

**Comment by garrett-laroy-johnson** [comment]
oo good good. I'll just render them in photoshop accordingly
