### ISSUE TITLE
Adaptive loading, permacomputing etc

### ISSUE THREAD

**Issue by parkerdavis1** [parkerdavis1/CCAM#89]
I would like to give users the option of disabling the animations on the CCAM website (I visited CCAM on my old computer yesterday and all the animations made the computer fan turn on, hah.) 

Any ideas as far as UI/UX to present this option to people? (I can take care of implementation details.)

**Comment by parkerdavis1** [comment]
Its not 100% ideal (being at the bottom of the page and not super findable and while very very cute... well, its cute) but I added a tortoise/hare next to the theme switcher to toggle animations on and off. I hope you like it!!!!! 🐢🐇

![Screenshot 2024-03-22 at 4 16 14 PM](https://github.com/parkerdavis1/CCAM/assets/92223355/a4a80dc6-4d2b-487a-93cd-ba17816a2add)

![Screenshot 2024-03-22 at 4 16 20 PM](https://github.com/parkerdavis1/CCAM/assets/92223355/bdbc4342-ed4b-4595-a09e-bc094077baf0)

**Comment by garrett-laroy-johnson** [comment]
Sooooo cute. I’m pro THIS!!!
