### ISSUE TITLE
Programs filters

### ISSUE THREAD

**Issue by parkerdavis1** [parkerdavis1/CCAM#9]
The programs page needs to be refactored to make the filters work. I can do this.

**Comment by parkerdavis1** [comment]
I have done a basic refactor of the programs page to make the filters work. (6a0879436fc2bccfdc2eb43281e193fa1287917f) 

Try it out here: https://ccam-staging.netlify.app/programs/

The annoying thing I hadn't realized is you cannot use .astro components inside of React/Preact components so I had to refactor several things to be react-y.

Still left to do: I think indicating the active filter should be more clear. Right now I set it so the active filter button text is bold. Do you have any ideas how to make it more clear what filter is active @ioanbutiu? Right now you deactivate the filter by clicking the active filter. I'm not thrilled with this UX but not sure what would be better. Ideas welcome!

There is definitely some cleanup that I need to do assuming that this reactive filter idea is something we definitely want.

**Comment by parkerdavis1** [comment]
Alternative: the initial programs page could be all programs, then clicking the filters would navigate you to a new page with the filtered events. Complexity would be lowered, URLs would hold all the state and be more bookmark-able. 

Maybe this was the intention all along, I sort of assumed the filters were meant to be app-like. The app filter is fine too, but the UX currently is a little confusing and the answer to me is not obvious how to make it more usable without a bunch of trying things out.

😎 anyways, happy new year my dudes! Keep on surfin' the web 🌊🏄🏼‍♀️

**Comment by parkerdavis1** [comment]
...and another point towards doing it web-style vs app-style: It becomes complicated to use Astro's built-in image optimization within react components. I just noticed that since the refactor, it is loading a full 2.5mb png for program cards. WOOOP.  I'm sure there'd be a way to wrangle in another image optimization plugin or a 3rd party service like Cloudinary, but man, who wants to do that!

I’ll probably refactor back to web-style sometime in the next week assuming there are no protestations. @ioanbutiu @garrett-laroy-johnson

**Comment by garrett-laroy-johnson** [comment]
It took me a second to understand the distinction, but "web style" seems to be sensible given the scale of materials within program. 

(this is probably already obvious, but right now clicking any of the three filters doesn't do anything for me).

**Comment by parkerdavis1** [comment]
yeah I started moving back to web-style and honed in the ViewTransitions stuff but haven't yet made the filters work again, should be pretty simple

**Comment by parkerdavis1** [comment]
This works again.
