### ISSUE TITLE
donate link

### ISSUE THREAD

**Issue by garrett-laroy-johnson** [parkerdavis1/CCAM#90]
I know this might not be the sexiest, but we need to get a donate link up soon: 
[link](
https://app.autobooks.co/pay/center-for-concrete-and-abstract-machines )

Do you mind if I add it to the nav bar? or is it not so simple?

**Comment by parkerdavis1** [comment]
Aesthetically it is getting cluttered but... its there now?
![Screenshot 2024-03-22 at 3 04 15 PM](https://github.com/parkerdavis1/CCAM/assets/92223355/90e76414-356f-468a-99c2-431ee2a262a5)

**Comment by parkerdavis1** [comment]
You can merge it into main if that seems fine
https://github.com/parkerdavis1/CCAM/commit/8584cc6c480de02b3d2fac806e09eb383d24a0b0

**Comment by garrett-laroy-johnson** [comment]
thank you Parker!!

**Comment by garrett-laroy-johnson** [comment]
So good. Appreciate you friend.
